name: Compile and install PHP from source
description: Compile and install PHP from source
inputs:
  branch:
    default: ''
    description: >
      php-src branch
runs:
  using: composite
  steps:
    - name: Checkout php-src repo
      uses: actions/checkout@v4
      with:
        repository: php/php-src
        path: .php-src
        ref: ${{ inputs.branch }}

    - name: Checkout curl repo
      uses: actions/checkout@v4
      with:
        repository: curl/curl
        path: .curl
        fetch-depth: 0

    - name: Checkout latest release tag
      shell: bash
      run: |
        cd .curl
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG
        cd ../

    - name: Install dependencies
      shell: bash
      run: |
        set -x

        export DEBIAN_FRONTEND=noninteractive
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update -y | true
        sudo apt build-dep libcurl4-openssl-dev curl -y
        sudo apt build-dep libcurl4-openssl-dev curl -y
        sudo apt install -y \
          libgsasl-dev \
          autoconf \
          gcc \
          make \
          unzip \
          bison \
          re2c \
          locales \
          ldap-utils \
          openssl \
          slapd \
          language-pack-de \
          libgmp-dev \
          libicu-dev \
          libtidy-dev \
          libenchant-2-dev \
          libbz2-dev \
          libsasl2-dev \
          libxpm-dev \
          libzip-dev \
          libsqlite3-dev \
          libsqlite3-mod-spatialite \
          libwebp-dev \
          libonig-dev \
          libxml2-dev \
          libxslt1-dev \
          libpq-dev \
          libreadline-dev \
          libldap2-dev \
          libsodium-dev \
          libargon2-dev \
          libmm-dev \
          libsnmp-dev \
          snmpd \
          snmp-mibs-downloader \
          freetds-dev \
          unixodbc-dev \
          llvm \
          clang \
          sendmail \
          firebird-dev \
          liblmdb-dev \
          libtokyocabinet-dev \
          libdb-dev \
          libqdbm-dev \
          libjpeg-dev \
          libpng-dev \
          libavif-dev \
          libfreetype6-dev \
          libc-client-dev \
          libkrb5-dev
        cd ..

    - name: Show existing env
      shell: bash
      run: |
        curl --version
        gcc -v

    - name: Configure Curl build
      shell: bash
      run: |
        set -x
        cd .curl
        autoreconf -fi
        ./configure --disable-symbol-hiding --enable-versioned-symbols	\
          --enable-threaded-resolver --with-lber-lib=lber		\
          --enable-websockets \
          --with-gssapi=/usr --with-nghttp2	\
          --includedir=/usr/include/$(DEB_HOST_MULTIARCH)		\
          --with-zsh-functions-dir=/usr/share/zsh/vendor-completions \
          --with-fish-functions-dir=/usr/share/fish/vendor_completions.d \
          --with-ca-path=/etc/ssl/certs \
          --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
          --without-libssh --with-libssh2 \
          --with-openssl \
          --enable-http           \
          --enable-ftp            \
          --enable-file           \
          --enable-ipfs           \
          --enable-ldap           \
          --enable-ldaps          \
          --enable-rtsp           \
          --enable-proxy          \
          --enable-dict           \
          --enable-telnet         \
          --enable-tftp           \
          --enable-pop3           \
          --enable-imap           \
          --enable-smb            \
          --enable-smtp           \
          --enable-gopher         \
          --enable-mqtt           \
          --enable-manual         \
          --enable-docs           \
          --enable-ipv6           \
          --enable-pthreads       \
          --enable-verbose        \
          --enable-sspi           \
          --enable-basic-auth     \
          --enable-bearer-auth    \
          --enable-digest-auth    \
          --enable-kerberos-auth  \
          --enable-negotiate-auth \
          --enable-aws            \
          --enable-ntlm           \
          --enable-tls-srp        \
          --enable-unix-sockets   \
          --enable-cookies        \
          --enable-socketpair     \
          --enable-sspi           \
          --enable-http-auth      \
          --with-imap             \
          --with-imap-ssl         \
          --with-kerberos
        
        cd ../

    - name: Compile Curl
      shell: bash
      run: |
        cd ./.curl
        make -j$(/usr/bin/nproc) >/dev/null
        cd ../

    - name: Install Curl
      shell: bash
      run: |
        set -x
        cd ./.curl
        sudo make install
        sudo ldconfig
        cd ../

    - name: Show version info
      shell: bash
      run: |
        curl --version

    - name: Configure build
      shell: bash
      run: |
          set -x
          cd .php-src
          ./buildconf --force
          ./configure \
            --enable-option-checking=fatal \
            --prefix=/usr \
            --enable-phpdbg \
            --enable-fpm \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pgsql \
            --with-pdo-pgsql \
            --with-pdo-sqlite \
            --enable-intl \
            --without-pear \
            --enable-gd \
            --with-jpeg \
            --with-webp \
            --with-avif \
            --with-freetype \
            --with-xpm \
            --enable-exif \
            --with-zip \
            --with-zlib \
            --enable-soap \
            --enable-xmlreader \
            --with-xsl \
            --with-tidy \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --with-readline \
            --enable-mbstring \
            --with-curl \
            --with-gettext \
            --enable-sockets \
            --with-bz2 \
            --with-openssl \
            --with-gmp \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --with-enchant=/usr \
            --enable-sysvmsg \
            --with-ffi \
            --with-ldap \
            --with-ldap-sasl \
            --with-password-argon2 \
            --with-mhash \
            --with-sodium \
            --enable-dba \
            --with-cdb \
            --enable-flatfile \
            --enable-inifile \
            --with-tcadb \
            --with-lmdb \
            --with-qdbm \
            --with-snmp \
            --with-unixODBC \
            --with-pdo-odbc=unixODBC,/usr \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d \
            --with-pdo-dblib \
            --enable-werror
          cd ../

    - name: Compile PHP
      shell: bash
      run: |
          cd ./.php-src
          make -j$(/usr/bin/nproc) >/dev/null
          cd ../

    - name: Install PHP
      shell: bash
      run: |
          set -x
          cd ./.php-src
          sudo make install
          sudo mkdir -p /etc/php.d
          sudo chmod 777 /etc/php.d
          cd ../

    - name: Enable opcache
      shell: bash
      run: |
        echo zend_extension=opcache.so >> /etc/php.d/opcache.ini
        echo opcache.enable=1 >> /etc/php.d/opcache.ini
        echo opcache.enable_cli=1 >> /etc/php.d/opcache.ini

    - name: Cleanup
      shell: bash
      run: |
        rm .php-src -Rf
